### ISSUE TITLE
Markkereiden korjaus

### ISSUE THREAD

**Issue by Turee** [vturpeinen/Terraces#6]
Antti kyseli apuja muttei ollu oikkia pushata repoon. Alhaalla kuitenkin fixin diff.

Fix:

```diff
@@ -25,8 +23,11 @@ class SimpleMap extends Component {
           //bootstrapURLKeys={{ key: /* YOUR KEY HERE */ }}
           defaultCenter={this.props.center}
           defaultZoom={this.props.zoom}
-          >
-          <SimplePlaceContainer places={this.props.restaurants} />
+        >
+          {this.props.restaurants.map(({ lat, lng }) => 
+            <SimplePlace lat={lat} lng={lng} text={'Roskapankki'} /* road circle */ />
+          )}
+
           <AnyReactComponent
             lat={60.1699}
             lng={24.9384}
```

**Comment by vturpeinen** [comment]
Moro,

Yllättäen ollaan melko päissämme kaikki. Voitko tehdä oman branchin jonne pushata fixin?

Suojattiin master yhdellä pullarilla joten myös se käy että teet PR ja joku muu kuin sinä hyväksyy :)

-Ville “The Scrum Master who facilitates beer, steak and basement”

**Comment by vturpeinen** [comment]
Kiitti, ihan tuollaisena ei toimi, ide antaa "unexpected symbol" viimeisestä aaltosulusta. Joku syntax error vain. "Turee" tee kaikista commiteista oma branch ja siitä pull request, suojattiin heti alkuun master niin että sinne ei voi kukaan pushata ilman pullaria ja vähintään 1 approval :) Tässä projektissa kaikilla taitaa olla käytössä siviilikone ja VS Code joten IDE eroavaisuuksia ei luultavasti esiinny.

**Comment by vturpeinen** [comment]
Marker fix implemented by Antti. Tested&merged to master.
